"""Replicates the SQLite backups produced by backup.py into Postgres.

Reads exclusively from the .bak-<timestamp> files backup.py already
produced -- never a live backend/data/*.db file. This is what keeps the
checksums recorded in the manifest and the rows actually inserted here
guaranteed to match: if this instead reopened the live file, a write
landing between backup.py and this step could make the two diverge.

One INSERT shape covers all three pk_kind values (identity/plain/
singleton): a BIGINT GENERATED BY DEFAULT AS IDENTITY column (chosen,
not GENERATED ALWAYS, specifically so a real future live-cutover insert
works normally) already accepts explicit values in a plain INSERT, so no
OVERRIDING SYSTEM VALUE clause is needed anywhere.
"""

import argparse
import json
import os
from pathlib import Path
from urllib.parse import urlparse

import psycopg
from dotenv import load_dotenv
from psycopg import sql

from app.migration import introspect
from app.migration.manifest import DOMAINS

DATA_DIR = Path(__file__).parent.parent.parent / "data"
DEFAULT_DSN = "postgresql://joshuapeters@localhost:5432/pcorp_migration_test"

_SQLITE_TYPE_MAP = {
    "INTEGER": "BIGINT",
    "TEXT": "TEXT",
    "REAL": "DOUBLE PRECISION",
    "NUMERIC": "DOUBLE PRECISION",
    "BLOB": "BYTEA",  # defensive -- no BLOB columns exist in any of the 12 dbs today
}


def _pg_type(sqlite_type: str) -> str:
    base = sqlite_type.split("(")[0].strip().upper()
    return _SQLITE_TYPE_MAP.get(base, "TEXT")


def resolve_dsn(cli_dsn: str | None) -> str:
    """CLI --dsn > MIGRATION_POSTGRES_DSN env var > local default.

    Falling back to a hardcoded *local* default is a deliberate safety
    feature, not just convenience: absent explicit configuration, this
    tool physically cannot target anything other than the one
    pre-approved local database.
    """
    if cli_dsn:
        return cli_dsn
    env_dsn = os.environ.get("MIGRATION_POSTGRES_DSN")
    if env_dsn:
        return env_dsn
    return DEFAULT_DSN


def require_local_or_confirmed(dsn: str, confirm_remote: bool) -> None:
    """Refuses a non-local DSN unless --confirm-remote was passed --
    defense-in-depth for once a real cloud DSN exists, so this tool can't
    be run against it out of habit.
    """
    host = urlparse(dsn).hostname or ""
    if host not in ("localhost", "127.0.0.1") and not confirm_remote:
        raise SystemExit(
            f"Refusing to target non-local host '{host}' without --confirm-remote. "
            "This tool is meant for local testing until a real cloud target is chosen."
        )


def _latest_manifest() -> Path:
    candidates = sorted(DATA_DIR.glob("migration_manifest_*.json"))
    if not candidates:
        raise SystemExit("No migration manifest found -- run backup.py first.")
    return candidates[-1]


def _column_def(name: str, pg_type: str, not_null: bool, is_pk: bool, pk_kind: str) -> sql.Composable:
    if is_pk:
        if pk_kind == "identity":
            return sql.SQL("{} BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY").format(
                sql.Identifier(name)
            )
        return sql.SQL("{} {} PRIMARY KEY").format(sql.Identifier(name), sql.SQL(pg_type))
    suffix = sql.SQL(" NOT NULL") if not_null else sql.SQL("")
    return sql.SQL("{} {}{}").format(sql.Identifier(name), sql.SQL(pg_type), suffix)


def _create_table(cur, schema_name: str, table_name: str, schema: introspect.TableSchema, pk_column: str, pk_kind: str) -> None:
    defs = [
        _column_def(col.name, _pg_type(col.sqlite_type), col.not_null, col.name == pk_column, pk_kind)
        for col in schema.columns
    ]
    # Deliberately not creating real FOREIGN KEY constraints here, even
    # for the 5 domains with declared intra-file REFERENCES clauses.
    # Found live (2026-09-10): PRAGMA foreign_keys is 0 on every one of
    # these databases (confirmed directly; grep of app/*.py shows it's
    # never turned on), so SQLite has never actually enforced any of
    # these -- they're documentation, not a live guarantee. Real,
    # currently-existing data already violates one (two alpha_mode.db
    # projects rows reference a clients row that doesn't exist; clients
    # is genuinely empty). Faithfully replicating *current behavior*
    # means preserving these columns as plain data, not upgrading them
    # into enforcement the source never had -- doing otherwise would
    # block real data from migrating over a constraint that was never
    # real. schema.foreign_keys is still read (introspect.py) and
    # available if a later stage deliberately decides to enforce these.
    stmt = sql.SQL("CREATE TABLE IF NOT EXISTS {}.{} ({})").format(
        sql.Identifier(schema_name),
        sql.Identifier(table_name),
        sql.SQL(", ").join(defs),
    )
    cur.execute(stmt)


def _upsert_rows(cur, schema_name: str, table_name: str, columns: list[str], pk_column: str, rows: list[tuple]) -> None:
    if not rows:
        return
    update_cols = [c for c in columns if c != pk_column]
    conflict_action = (
        sql.SQL("UPDATE SET {}").format(
            sql.SQL(", ").join(
                sql.SQL("{0} = EXCLUDED.{0}").format(sql.Identifier(c)) for c in update_cols
            )
        )
        if update_cols
        else sql.SQL("NOTHING")
    )
    insert_stmt = sql.SQL("INSERT INTO {}.{} ({}) VALUES ({}) ON CONFLICT ({}) DO {}").format(
        sql.Identifier(schema_name),
        sql.Identifier(table_name),
        sql.SQL(", ").join(map(sql.Identifier, columns)),
        sql.SQL(", ").join(sql.Placeholder() for _ in columns),
        sql.Identifier(pk_column),
        conflict_action,
    )
    cur.executemany(insert_stmt, rows)


def _fix_sequence(cur, schema_name: str, table_name: str, pk_column: str) -> None:
    """Correct 3-arg setval: for a currently-empty table, MAX(id) IS NULL
    so is_called=false, meaning the next real insert correctly gets id 1
    rather than skipping straight to 2 (which the naive 2-arg
    setval(seq, COALESCE(MAX(id), 1)) form would do).
    """
    qualified = f"{schema_name}.{table_name}"
    cur.execute(
        sql.SQL(
            "SELECT setval(pg_get_serial_sequence({}, {}), "
            "COALESCE((SELECT MAX({}) FROM {}.{}), 1), "
            "(SELECT MAX({}) FROM {}.{}) IS NOT NULL)"
        ).format(
            sql.Literal(qualified),
            sql.Literal(pk_column),
            sql.Identifier(pk_column),
            sql.Identifier(schema_name),
            sql.Identifier(table_name),
            sql.Identifier(pk_column),
            sql.Identifier(schema_name),
            sql.Identifier(table_name),
        )
    )


def run(dsn: str, manifest_path: Path | None = None) -> None:
    manifest_path = manifest_path or _latest_manifest()
    manifest = json.loads(manifest_path.read_text())

    with psycopg.connect(dsn) as conn:
        for domain in DOMAINS:
            domain_manifest = manifest["domains"][domain.name]
            backup_path = domain_manifest["backup_path"]

            with conn.cursor() as cur:
                cur.execute(sql.SQL("CREATE SCHEMA IF NOT EXISTS {}").format(sql.Identifier(domain.name)))

            for table in domain.tables:
                table_manifest = domain_manifest["tables"][table.name]
                columns = table_manifest["columns"]
                schema = introspect.read_table_schema(backup_path, table.name)

                with conn.cursor() as cur:
                    _create_table(cur, domain.name, table.name, schema, table.pk_column, table.pk_kind)

                rows = introspect.read_all_rows(backup_path, table.name, columns)
                with conn.cursor() as cur:
                    _upsert_rows(cur, domain.name, table.name, columns, table.pk_column, rows)
                    if table.pk_kind == "identity":
                        _fix_sequence(cur, domain.name, table.name, table.pk_column)

            conn.commit()
            print(f"Replicated domain: {domain.name}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Replicate SQLite backups into Postgres")
    parser.add_argument("--dsn", default=None)
    parser.add_argument("--confirm-remote", action="store_true")
    parser.add_argument("--manifest", default=None)
    args = parser.parse_args()

    load_dotenv(Path(__file__).parent.parent.parent / ".env")
    dsn = resolve_dsn(args.dsn)
    require_local_or_confirmed(dsn, args.confirm_remote)

    manifest_path = Path(args.manifest) if args.manifest else None
    run(dsn, manifest_path)


if __name__ == "__main__":
    main()
