"""
General, cross-business task tracking — the concrete, trackable-over-time
slice of the Operations Agent's responsibilities (SOPs, workflow advice,
project planning, bottleneck-spotting, and automation suggestions stay
purely conversational for now; see operations_agent.py). Confirmed
decision (2026-07-31): tasks aren't scoped to any one business (not tied
to Alpha Mode Media's clients/projects) — genuinely general, spanning
whatever Joshua is actually working on across all of his businesses.

Its own SQLite file (operations.db), same "genuinely separate domain"
reasoning already applied to alpha_mode.db — not commingled with
pcorp.db's conversations/memory, and not merged into Alpha Mode Media's
own data either, since tasks cut across all businesses, not just one.
"""

from pathlib import Path
from typing import Any

import aiosqlite

DB_PATH = Path(__file__).parent.parent / "data" / "operations.db"


async def init_operations_db() -> None:
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    async with aiosqlite.connect(DB_PATH) as db:
        await db.execute(
            """
            CREATE TABLE IF NOT EXISTS tasks (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                title TEXT NOT NULL,
                status TEXT NOT NULL DEFAULT 'open',
                area TEXT,
                due_date TEXT,
                notes TEXT,
                created_at TEXT NOT NULL DEFAULT (datetime('now'))
            )
            """
        )
        # Migration path: tasks existed before deleted_at did. Real gap
        # found 2026-08-10: a test task (bad due date, never real) had no
        # way to be removed -- only add_task/update_task_status existed,
        # and marking a test row "done" would have been dishonest. Soft
        # delete, not a real DELETE, same reasoning as memory_records'
        # deleted_at -- keeps delete_task in SECURITY.md's "Regular"
        # auto-allowed tier (reversible), not "needs confirmation."
        cursor = await db.execute("PRAGMA table_info(tasks)")
        columns = {row[1] async for row in cursor}
        if "deleted_at" not in columns:
            await db.execute("ALTER TABLE tasks ADD COLUMN deleted_at TEXT")
        await db.commit()


async def add_task(
    title: str,
    area: str | None = None,
    due_date: str | None = None,
    notes: str | None = None,
    postgres_conn: Any = None,
) -> str:
    if postgres_conn is not None:
        return await _add_task_postgres(postgres_conn, title, area, due_date, notes)
    return await _add_task_sqlite(title, area, due_date, notes)


async def _add_task_sqlite(title: str, area: str | None, due_date: str | None, notes: str | None) -> str:
    async with aiosqlite.connect(DB_PATH) as db:
        await db.execute(
            "INSERT INTO tasks (title, area, due_date, notes) VALUES (?, ?, ?, ?)",
            (title, area, due_date, notes),
        )
        await db.commit()
        return title


async def _add_task_postgres(conn: Any, title: str, area: str | None, due_date: str | None, notes: str | None) -> str:
    # No id column -- BIGINT GENERATED BY DEFAULT AS IDENTITY auto-generates
    # it, same as SQLite's AUTOINCREMENT. status/created_at supplied
    # explicitly -- same missing-DEFAULT gap already found and fixed once
    # for personal.goals/habits (Stage 3's replicate.py doesn't carry
    # SQLite DEFAULT clauses into the Postgres DDL), applied proactively
    # here rather than rediscovering the same NotNullViolation again.
    async with conn.cursor() as cur:
        await cur.execute(
            "INSERT INTO operations.tasks (title, status, area, due_date, notes, created_at) "
            "VALUES (%s, 'open', %s, %s, %s, (now() AT TIME ZONE 'utc'))",
            (title, area, due_date, notes),
        )
    await conn.commit()
    return title


async def _find_task_id(db: aiosqlite.Connection, identifier: str) -> int | None:
    # Shared by update_task_status/delete_task -- exact title match
    # (case-insensitive), then substring, most recent first. Frank
    # doesn't see raw task IDs, same reasoning as memory's forget-by-title.
    cursor = await db.execute(
        "SELECT id FROM tasks WHERE title = ? COLLATE NOCASE AND deleted_at IS NULL ORDER BY id DESC LIMIT 1",
        (identifier,),
    )
    row = await cursor.fetchone()
    if row is None:
        cursor = await db.execute(
            "SELECT id FROM tasks WHERE title LIKE ? AND deleted_at IS NULL ORDER BY id DESC LIMIT 1",
            (f"%{identifier}%",),
        )
        row = await cursor.fetchone()
    return row["id"] if row else None


async def _find_task_id_postgres(conn: Any, identifier: str) -> int | None:
    # ILIKE, not LIKE -- same case-sensitivity fix already proven necessary
    # for personal_db.py's _find_goal_id_postgres (SQLite's LIKE/COLLATE
    # NOCASE are case-insensitive by default; Postgres's LIKE is not).
    async with conn.cursor() as cur:
        await cur.execute(
            "SELECT id FROM operations.tasks WHERE title ILIKE %s AND deleted_at IS NULL ORDER BY id DESC LIMIT 1",
            (identifier,),
        )
        row = await cur.fetchone()
        if row is None:
            await cur.execute(
                "SELECT id FROM operations.tasks WHERE title ILIKE %s AND deleted_at IS NULL ORDER BY id DESC LIMIT 1",
                (f"%{identifier}%",),
            )
            row = await cur.fetchone()
        return row[0] if row else None


async def update_task_status(identifier: str, new_status: str, postgres_conn: Any = None) -> bool:
    if postgres_conn is not None:
        return await _update_task_status_postgres(postgres_conn, identifier, new_status)
    return await _update_task_status_sqlite(identifier, new_status)


async def _update_task_status_sqlite(identifier: str, new_status: str) -> bool:
    async with aiosqlite.connect(DB_PATH) as db:
        db.row_factory = aiosqlite.Row
        task_id = await _find_task_id(db, identifier)
        if task_id is None:
            return False
        await db.execute("UPDATE tasks SET status = ? WHERE id = ?", (new_status, task_id))
        await db.commit()
        return True


async def _update_task_status_postgres(conn: Any, identifier: str, new_status: str) -> bool:
    task_id = await _find_task_id_postgres(conn, identifier)
    if task_id is None:
        return False
    async with conn.cursor() as cur:
        await cur.execute("UPDATE operations.tasks SET status = %s WHERE id = %s", (new_status, task_id))
    await conn.commit()
    return True


async def delete_task(identifier: str, postgres_conn: Any = None) -> str | None:
    """Soft delete -- for tasks that shouldn't have existed at all (test
    data, a mistaken entry), distinct from update_task_status's "done"/
    "blocked"/etc., which is for tasks that genuinely happened. Returns
    the deleted task's real title (so Frank can confirm what happened),
    or None if nothing matched."""
    if postgres_conn is not None:
        return await _delete_task_postgres(postgres_conn, identifier)
    return await _delete_task_sqlite(identifier)


async def _delete_task_sqlite(identifier: str) -> str | None:
    async with aiosqlite.connect(DB_PATH) as db:
        db.row_factory = aiosqlite.Row
        task_id = await _find_task_id(db, identifier)
        if task_id is None:
            return None
        cursor = await db.execute("SELECT title FROM tasks WHERE id = ?", (task_id,))
        row = await cursor.fetchone()
        await db.execute("UPDATE tasks SET deleted_at = datetime('now') WHERE id = ?", (task_id,))
        await db.commit()
        return row["title"]


async def _delete_task_postgres(conn: Any, identifier: str) -> str | None:
    task_id = await _find_task_id_postgres(conn, identifier)
    if task_id is None:
        return None
    async with conn.cursor() as cur:
        await cur.execute("SELECT title FROM operations.tasks WHERE id = %s", (task_id,))
        row = await cur.fetchone()
        # Soft delete, same as the SQLite path -- nothing is ever hard-deleted.
        await cur.execute("UPDATE operations.tasks SET deleted_at = (now() AT TIME ZONE 'utc') WHERE id = %s", (task_id,))
    await conn.commit()
    return row[0]


async def list_open_tasks(postgres_conn: Any = None) -> list[dict]:
    """Structured form of the same data summarize_open_tasks() formats as
    text -- for the real GET /operations/tasks endpoint (the new "Agents"
    nav section), not the system-prompt block."""
    if postgres_conn is not None:
        return await _list_open_tasks_postgres(postgres_conn)
    return await _list_open_tasks_sqlite()


async def _list_open_tasks_sqlite() -> list[dict]:
    async with aiosqlite.connect(DB_PATH) as db:
        db.row_factory = aiosqlite.Row
        cursor = await db.execute(
            "SELECT id, title, status, area, due_date, notes, created_at FROM tasks "
            "WHERE status != 'done' AND deleted_at IS NULL ORDER BY id DESC"
        )
        rows = await cursor.fetchall()
        return [
            {
                "id": row["id"],
                "title": row["title"],
                "status": row["status"],
                "area": row["area"],
                "due_date": row["due_date"],
                "notes": row["notes"],
                "created_at": row["created_at"],
            }
            for row in rows
        ]


async def _list_open_tasks_postgres(conn: Any) -> list[dict]:
    async with conn.cursor() as cur:
        await cur.execute(
            "SELECT id, title, status, area, due_date, notes, created_at FROM operations.tasks "
            "WHERE status != 'done' AND deleted_at IS NULL ORDER BY id DESC"
        )
        rows = await cur.fetchall()
        return [
            {
                "id": r[0],
                "title": r[1],
                "status": r[2],
                "area": r[3],
                "due_date": r[4],
                "notes": r[5],
                "created_at": str(r[6]) if r[6] is not None else None,
            }
            for r in rows
        ]


async def summarize_open_tasks(postgres_conn: Any = None) -> str:
    """Fine to load in full every turn at this scale -- same reasoning as
    memory_records and Alpha Mode Media's snapshot; revisit if this ever
    grows large enough to need real filtering/ranking.

    postgres_conn threaded through for the same reason personal_db.py's
    summarize() needs it -- this feeds both Frank's own system prompt
    (build_operations_block()) and consult_operations_agent's delegated
    context, and both need to read the same live source as list_open_tasks/
    the write tools, not silently stay on SQLite after a real cutover."""
    rows = await _summarize_open_tasks_rows(postgres_conn)
    if not rows:
        return ""
    lines = ["Open tasks:"]
    for row in rows:
        area = f" [{row['area']}]" if row["area"] else ""
        due = f", due {row['due_date']}" if row["due_date"] else ""
        notes = f" — {row['notes']}" if row["notes"] else ""
        lines.append(f"  - {row['title']}{area}{due}{notes}")
    return "\n".join(lines)


async def _summarize_open_tasks_rows(postgres_conn: Any) -> list[dict]:
    if postgres_conn is not None:
        async with postgres_conn.cursor() as cur:
            await cur.execute(
                "SELECT title, area, due_date, notes FROM operations.tasks "
                "WHERE status != 'done' AND deleted_at IS NULL ORDER BY id"
            )
            rows = await cur.fetchall()
            return [{"title": r[0], "area": r[1], "due_date": r[2], "notes": r[3]} for r in rows]
    async with aiosqlite.connect(DB_PATH) as db:
        db.row_factory = aiosqlite.Row
        cursor = await db.execute(
            "SELECT title, area, due_date, notes FROM tasks WHERE status != 'done' AND deleted_at IS NULL ORDER BY id"
        )
        rows = await cursor.fetchall()
        return [dict(r) for r in rows]
