"""
Goals and habits -- the deliberately narrow slice of AGENTS_VISION.md's
Personal Division scoped for real (2026-08-17), after Joshua explicitly
chose this over the full Life Agent vision (which also covers marriage,
health, family, journal, reflection -- all still fenced off, per
ROADMAP.md's "sensitive-material policy" note and PERSONALITY_SPEC.md's
Phase 1 privacy caveat). No delegation layer here on purpose: unlike
Operations/Alpha Mode, there's no consult_personal_agent tool and no
personal_agent.py -- just plain CRUD tools (personal_tools.py), same
shape as memory.py's save_memory/forget_memory. A persona giving
commentary or encouragement on goals/habits risks drifting toward
advice, which wasn't the ask; Frank (or this data layer) just remembers
and displays what it's told.

Its own SQLite file (personal.db), same "genuinely separate domain"
reasoning as alpha_mode.db/operations.db. Like every file under
backend/data/, this is gitignored -- nothing written here ever reaches
GitHub.
"""

from pathlib import Path
from typing import Any

import aiosqlite

DB_PATH = Path(__file__).parent.parent / "data" / "personal.db"


async def init_personal_db() -> None:
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    async with aiosqlite.connect(DB_PATH) as db:
        await db.execute(
            """
            CREATE TABLE IF NOT EXISTS goals (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                title TEXT NOT NULL,
                status TEXT NOT NULL DEFAULT 'active',
                target_date TEXT,
                notes TEXT,
                created_at TEXT NOT NULL DEFAULT (datetime('now')),
                deleted_at TEXT
            )
            """
        )
        await db.execute(
            """
            CREATE TABLE IF NOT EXISTS habits (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                title TEXT NOT NULL,
                cadence TEXT,
                notes TEXT,
                created_at TEXT NOT NULL DEFAULT (datetime('now')),
                deleted_at TEXT
            )
            """
        )
        await db.commit()


async def add_goal(
    title: str, target_date: str | None = None, notes: str | None = None, postgres_conn: Any = None
) -> str:
    if postgres_conn is not None:
        return await _add_goal_postgres(postgres_conn, title, target_date, notes)
    return await _add_goal_sqlite(title, target_date, notes)


async def _add_goal_sqlite(title: str, target_date: str | None, notes: str | None) -> str:
    async with aiosqlite.connect(DB_PATH) as db:
        await db.execute(
            "INSERT INTO goals (title, target_date, notes) VALUES (?, ?, ?)",
            (title, target_date, notes),
        )
        await db.commit()
        return title


async def _add_goal_postgres(conn: Any, title: str, target_date: str | None, notes: str | None) -> str:
    # No id column here -- the BIGINT GENERATED BY DEFAULT AS IDENTITY
    # column (created by the Stage 3 migration tooling) auto-generates it,
    # same as SQLite's AUTOINCREMENT does today; the caller never sees it.
    #
    # status/created_at ARE supplied explicitly -- a real bug found live:
    # Stage 3's replicate.py deliberately doesn't replicate SQLite's
    # DEFAULT clauses into the Postgres DDL (documented at the time as
    # "Stage 5's concern"), so personal.goals.status/created_at are
    # NOT NULL with no default in Postgres, unlike the SQLite table which
    # has DEFAULT 'active'/DEFAULT (datetime('now')). Omitting them here
    # (matching the SQLite INSERT's shape exactly) raised a real
    # NotNullViolation rather than silently defaulting -- confirmed no
    # partial row was left (Postgres rolled the failed INSERT back
    # atomically) before this fix.
    async with conn.cursor() as cur:
        await cur.execute(
            "INSERT INTO personal.goals (title, status, target_date, notes, created_at) "
            "VALUES (%s, 'active', %s, %s, now())",
            (title, target_date, notes),
        )
    await conn.commit()
    return title


async def _find_goal_id(db: aiosqlite.Connection, identifier: str) -> int | None:
    cursor = await db.execute(
        "SELECT id FROM goals WHERE title = ? COLLATE NOCASE AND deleted_at IS NULL ORDER BY id DESC LIMIT 1",
        (identifier,),
    )
    row = await cursor.fetchone()
    if row is None:
        cursor = await db.execute(
            "SELECT id FROM goals WHERE title LIKE ? AND deleted_at IS NULL ORDER BY id DESC LIMIT 1",
            (f"%{identifier}%",),
        )
        row = await cursor.fetchone()
    return row["id"] if row else None


async def _find_goal_id_postgres(conn: Any, identifier: str) -> int | None:
    # SQLite's LIKE (and the COLLATE NOCASE exact match above) are
    # case-insensitive for ASCII by default; Postgres's LIKE is
    # case-sensitive -- ILIKE is the real equivalent for both steps, not
    # LIKE. Using plain LIKE here would be a live behavior regression
    # (e.g. "mark 'read more books' done" failing to match a stored
    # "Read More Books"), found during design, not assumed away.
    async with conn.cursor() as cur:
        await cur.execute(
            "SELECT id FROM personal.goals WHERE title ILIKE %s AND deleted_at IS NULL ORDER BY id DESC LIMIT 1",
            (identifier,),
        )
        row = await cur.fetchone()
        if row is None:
            await cur.execute(
                "SELECT id FROM personal.goals WHERE title ILIKE %s AND deleted_at IS NULL ORDER BY id DESC LIMIT 1",
                (f"%{identifier}%",),
            )
            row = await cur.fetchone()
        return row[0] if row else None


async def update_goal_status(identifier: str, new_status: str, postgres_conn: Any = None) -> bool:
    if postgres_conn is not None:
        return await _update_goal_status_postgres(postgres_conn, identifier, new_status)
    return await _update_goal_status_sqlite(identifier, new_status)


async def _update_goal_status_sqlite(identifier: str, new_status: str) -> bool:
    async with aiosqlite.connect(DB_PATH) as db:
        db.row_factory = aiosqlite.Row
        goal_id = await _find_goal_id(db, identifier)
        if goal_id is None:
            return False
        await db.execute("UPDATE goals SET status = ? WHERE id = ?", (new_status, goal_id))
        await db.commit()
        return True


async def _update_goal_status_postgres(conn: Any, identifier: str, new_status: str) -> bool:
    goal_id = await _find_goal_id_postgres(conn, identifier)
    if goal_id is None:
        return False
    async with conn.cursor() as cur:
        await cur.execute("UPDATE personal.goals SET status = %s WHERE id = %s", (new_status, goal_id))
    await conn.commit()
    return True


async def delete_goal(identifier: str, postgres_conn: Any = None) -> str | None:
    if postgres_conn is not None:
        return await _delete_goal_postgres(postgres_conn, identifier)
    return await _delete_goal_sqlite(identifier)


async def _delete_goal_sqlite(identifier: str) -> str | None:
    async with aiosqlite.connect(DB_PATH) as db:
        db.row_factory = aiosqlite.Row
        goal_id = await _find_goal_id(db, identifier)
        if goal_id is None:
            return None
        cursor = await db.execute("SELECT title FROM goals WHERE id = ?", (goal_id,))
        row = await cursor.fetchone()
        await db.execute("UPDATE goals SET deleted_at = datetime('now') WHERE id = ?", (goal_id,))
        await db.commit()
        return row["title"]


async def _delete_goal_postgres(conn: Any, identifier: str) -> str | None:
    goal_id = await _find_goal_id_postgres(conn, identifier)
    if goal_id is None:
        return None
    async with conn.cursor() as cur:
        await cur.execute("SELECT title FROM personal.goals WHERE id = %s", (goal_id,))
        row = await cur.fetchone()
        # Soft delete, same as the SQLite path -- nothing is ever hard-deleted.
        await cur.execute("UPDATE personal.goals SET deleted_at = now() WHERE id = %s", (goal_id,))
    await conn.commit()
    return row[0]


async def add_habit(
    title: str, cadence: str | None = None, notes: str | None = None, postgres_conn: Any = None
) -> str:
    if postgres_conn is not None:
        return await _add_habit_postgres(postgres_conn, title, cadence, notes)
    return await _add_habit_sqlite(title, cadence, notes)


async def _add_habit_sqlite(title: str, cadence: str | None, notes: str | None) -> str:
    async with aiosqlite.connect(DB_PATH) as db:
        await db.execute(
            "INSERT INTO habits (title, cadence, notes) VALUES (?, ?, ?)",
            (title, cadence, notes),
        )
        await db.commit()
        return title


async def _add_habit_postgres(conn: Any, title: str, cadence: str | None, notes: str | None) -> str:
    # created_at supplied explicitly -- same NOT NULL/no-default gap as
    # _add_goal_postgres above (personal.habits.created_at has no
    # Postgres-side default either).
    async with conn.cursor() as cur:
        await cur.execute(
            "INSERT INTO personal.habits (title, cadence, notes, created_at) VALUES (%s, %s, %s, now())",
            (title, cadence, notes),
        )
    await conn.commit()
    return title


async def delete_habit(identifier: str, postgres_conn: Any = None) -> str | None:
    if postgres_conn is not None:
        return await _delete_habit_postgres(postgres_conn, identifier)
    return await _delete_habit_sqlite(identifier)


async def _delete_habit_sqlite(identifier: str) -> str | None:
    async with aiosqlite.connect(DB_PATH) as db:
        db.row_factory = aiosqlite.Row
        cursor = await db.execute(
            "SELECT id, title FROM habits WHERE title = ? COLLATE NOCASE AND deleted_at IS NULL ORDER BY id DESC LIMIT 1",
            (identifier,),
        )
        row = await cursor.fetchone()
        if row is None:
            cursor = await db.execute(
                "SELECT id, title FROM habits WHERE title LIKE ? AND deleted_at IS NULL ORDER BY id DESC LIMIT 1",
                (f"%{identifier}%",),
            )
            row = await cursor.fetchone()
        if row is None:
            return None
        await db.execute("UPDATE habits SET deleted_at = datetime('now') WHERE id = ?", (row["id"],))
        await db.commit()
        return row["title"]


async def _delete_habit_postgres(conn: Any, identifier: str) -> str | None:
    # Same ILIKE reasoning as _find_goal_id_postgres above.
    async with conn.cursor() as cur:
        await cur.execute(
            "SELECT id, title FROM personal.habits WHERE title ILIKE %s AND deleted_at IS NULL "
            "ORDER BY id DESC LIMIT 1",
            (identifier,),
        )
        row = await cur.fetchone()
        if row is None:
            await cur.execute(
                "SELECT id, title FROM personal.habits WHERE title ILIKE %s AND deleted_at IS NULL "
                "ORDER BY id DESC LIMIT 1",
                (f"%{identifier}%",),
            )
            row = await cur.fetchone()
        if row is None:
            return None
        await cur.execute("UPDATE personal.habits SET deleted_at = now() WHERE id = %s", (row[0],))
    await conn.commit()
    return row[1]


async def dashboard_snapshot(postgres_conn: Any = None) -> dict:
    """Backs GET /personal/dashboard (the desktop tab).

    Stage 4 prep (2026-09-10): a proof-of-concept dual-backend read. The
    route (main.py) passes a live psycopg AsyncConnection here only when
    DATA_BACKEND=postgres; otherwise this stays exactly today's SQLite
    path, untouched. Every write in this file (add_goal, update_goal_status,
    delete_goal, add_habit, delete_habit) is deliberately NOT part of this --
    Stage 4 is reads only, writes are Stage 5.
    """
    if postgres_conn is not None:
        return await _dashboard_snapshot_postgres(postgres_conn)
    return await _dashboard_snapshot_sqlite()


async def _dashboard_snapshot_sqlite() -> dict:
    async with aiosqlite.connect(DB_PATH) as db:
        db.row_factory = aiosqlite.Row
        cursor = await db.execute(
            "SELECT id, title, status, target_date, notes, created_at FROM goals "
            "WHERE deleted_at IS NULL ORDER BY id DESC"
        )
        goals = [dict(r) for r in await cursor.fetchall()]

        cursor = await db.execute(
            "SELECT id, title, cadence, notes, created_at FROM habits "
            "WHERE deleted_at IS NULL ORDER BY id DESC"
        )
        habits = [dict(r) for r in await cursor.fetchall()]

    return {"goals": goals, "habits": habits}


async def _dashboard_snapshot_postgres(conn: Any) -> dict:
    """Reads the same shape from personal.goals/personal.habits -- the
    exact schema/column names the Stage 3 migration tooling already
    creates and populates (backend/app/migration/manifest.py), so no new
    mapping is needed here. created_at/target_date come back as real
    Postgres types (str/datetime, not always plain str like SQLite) --
    str()'d explicitly so the JSON shape matches the SQLite path exactly.
    """
    async with conn.cursor() as cur:
        await cur.execute(
            "SELECT id, title, status, target_date, notes, created_at FROM personal.goals "
            "WHERE deleted_at IS NULL ORDER BY id DESC"
        )
        goal_rows = await cur.fetchall()
        goals = [
            {
                "id": r[0],
                "title": r[1],
                "status": r[2],
                "target_date": str(r[3]) if r[3] is not None else None,
                "notes": r[4],
                "created_at": str(r[5]) if r[5] is not None else None,
            }
            for r in goal_rows
        ]

        await cur.execute(
            "SELECT id, title, cadence, notes, created_at FROM personal.habits "
            "WHERE deleted_at IS NULL ORDER BY id DESC"
        )
        habit_rows = await cur.fetchall()
        habits = [
            {
                "id": r[0],
                "title": r[1],
                "cadence": r[2],
                "notes": r[3],
                "created_at": str(r[4]) if r[4] is not None else None,
            }
            for r in habit_rows
        ]

    return {"goals": goals, "habits": habits}


async def summarize() -> str:
    """Plain-text snapshot, same style as operations_db.summarize_open_tasks()
    -- not currently injected into Frank's own system prompt (this stays
    display-only for now, no consult agent to feed), kept for parity with
    the other domains' summarize() functions and available if that
    changes later."""
    snapshot = await dashboard_snapshot()
    if not snapshot["goals"] and not snapshot["habits"]:
        return ""
    lines: list[str] = []
    if snapshot["goals"]:
        active = [g for g in snapshot["goals"] if g["status"] == "active"]
        lines.append(f"Goals ({len(active)} active of {len(snapshot['goals'])} total):")
        for g in active:
            due = f", target {g['target_date']}" if g["target_date"] else ""
            lines.append(f"  - {g['title']}{due}")
    if snapshot["habits"]:
        lines.append(f"Habits tracked ({len(snapshot['habits'])}):")
        for h in snapshot["habits"]:
            cadence = f" ({h['cadence']})" if h["cadence"] else ""
            lines.append(f"  - {h['title']}{cadence}")
    return "\n".join(lines)
