"""
Approval-gated trade execution (2026-09-22) -- the only responsible version
of "can a trading agent trade for me" Josh asked about: the agent proposes
a specific trade, Josh approves or rejects it individually on his phone or
desktop, and only an approved proposal ever reaches the real account, via
a separate MQL5 Expert Advisor (PCorpExecutionBridge.mq5) that never runs
unattended logic of its own -- it only executes what a human already
approved here. See the plan doc for the full design; this module is just
the proposal ledger, same "genuinely separate domain, own table" reasoning
as trade_intelligence_db.py's own trades table.

Same dual-backend/CHECK-constraint/soft-delete shape as trade_intelligence_
db.py, same reason: real hard-enforced vocabularies (direction/status)
need real CHECK constraints, and the Stage 3/4 migration tool
(app/migration/replicate.py) never carries those over -- this table's
Postgres side is created by real inline DDL in init_trade_proposals_db,
not that pipeline.

Own SQLite file (trade_proposals.db) and own Postgres schema
(trade_proposals). Like every file under backend/data/, gitignored --
nothing written here ever reaches GitHub.
"""

from pathlib import Path
from typing import Any

import aiosqlite

DB_PATH = Path(__file__).parent.parent / "data" / "trade_proposals.db"

DIRECTIONS = ("long", "short")
STATUSES = ("pending", "approved", "rejected", "expired", "executed", "failed")

_PROPOSAL_COLUMNS = (
    "id", "symbol", "direction", "entry_price", "stop_loss", "take_profit", "risk_pct",
    "computed_lots_estimate", "reasoning", "status", "created_at", "resolved_at",
    "command_written_at", "executed_ticket", "executed_result",
)


async def init_trade_proposals_db(postgres_conn: Any = None) -> None:
    if postgres_conn is not None:
        await _init_postgres(postgres_conn)
        return
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    async with aiosqlite.connect(DB_PATH) as db:
        await db.execute(
            f"""
            CREATE TABLE IF NOT EXISTS trade_proposals (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                symbol TEXT NOT NULL,
                direction TEXT NOT NULL CHECK (direction IN {DIRECTIONS}),
                entry_price REAL NOT NULL,
                stop_loss REAL NOT NULL,
                take_profit REAL NOT NULL,
                risk_pct REAL NOT NULL,
                computed_lots_estimate REAL,
                reasoning TEXT NOT NULL,
                status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN {STATUSES}),
                created_at TEXT NOT NULL DEFAULT (datetime('now')),
                resolved_at TEXT,
                command_written_at TEXT,
                executed_ticket TEXT,
                executed_result TEXT,
                deleted_at TEXT
            )
            """
        )
        await db.commit()


async def _init_postgres(conn: Any) -> None:
    async with conn.cursor() as cur:
        await cur.execute("CREATE SCHEMA IF NOT EXISTS trade_proposals")
        await cur.execute(
            f"""
            CREATE TABLE IF NOT EXISTS trade_proposals.proposals (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                symbol TEXT NOT NULL,
                direction TEXT NOT NULL CHECK (direction IN {DIRECTIONS}),
                entry_price DOUBLE PRECISION NOT NULL,
                stop_loss DOUBLE PRECISION NOT NULL,
                take_profit DOUBLE PRECISION NOT NULL,
                risk_pct DOUBLE PRECISION NOT NULL,
                computed_lots_estimate DOUBLE PRECISION,
                reasoning TEXT NOT NULL,
                status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN {STATUSES}),
                created_at TEXT NOT NULL,
                resolved_at TEXT,
                command_written_at TEXT,
                executed_ticket TEXT,
                executed_result TEXT,
                deleted_at TEXT
            )
            """
        )
    await conn.commit()


async def create_proposal(
    symbol: str,
    direction: str,
    entry_price: float,
    stop_loss: float,
    take_profit: float,
    risk_pct: float,
    reasoning: str,
    computed_lots_estimate: float | None = None,
    postgres_conn: Any = None,
) -> int:
    if postgres_conn is not None:
        async with postgres_conn.cursor() as cur:
            await cur.execute(
                "INSERT INTO trade_proposals.proposals "
                "(symbol, direction, entry_price, stop_loss, take_profit, risk_pct, "
                "computed_lots_estimate, reasoning, status, created_at) "
                "VALUES (%s, %s, %s, %s, %s, %s, %s, %s, 'pending', (now() AT TIME ZONE 'utc')) "
                "RETURNING id",
                (symbol, direction, entry_price, stop_loss, take_profit, risk_pct, computed_lots_estimate, reasoning),
            )
            (new_id,) = await cur.fetchone()
        await postgres_conn.commit()
        return new_id
    async with aiosqlite.connect(DB_PATH) as db:
        cursor = await db.execute(
            "INSERT INTO trade_proposals "
            "(symbol, direction, entry_price, stop_loss, take_profit, risk_pct, computed_lots_estimate, reasoning) "
            "VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
            (symbol, direction, entry_price, stop_loss, take_profit, risk_pct, computed_lots_estimate, reasoning),
        )
        await db.commit()
        return cursor.lastrowid


async def list_proposals(status: str | None = None, postgres_conn: Any = None) -> list[dict]:
    if postgres_conn is not None:
        async with postgres_conn.cursor() as cur:
            if status is not None:
                await cur.execute(
                    f"SELECT {', '.join(_PROPOSAL_COLUMNS)} FROM trade_proposals.proposals "
                    "WHERE deleted_at IS NULL AND status = %s ORDER BY created_at DESC",
                    (status,),
                )
            else:
                await cur.execute(
                    f"SELECT {', '.join(_PROPOSAL_COLUMNS)} FROM trade_proposals.proposals "
                    "WHERE deleted_at IS NULL ORDER BY created_at DESC"
                )
            rows = await cur.fetchall()
            return [dict(zip(_PROPOSAL_COLUMNS, row)) for row in rows]
    async with aiosqlite.connect(DB_PATH) as db:
        db.row_factory = aiosqlite.Row
        if status is not None:
            cursor = await db.execute(
                f"SELECT {', '.join(_PROPOSAL_COLUMNS)} FROM trade_proposals "
                "WHERE deleted_at IS NULL AND status = ? ORDER BY created_at DESC",
                (status,),
            )
        else:
            cursor = await db.execute(
                f"SELECT {', '.join(_PROPOSAL_COLUMNS)} FROM trade_proposals "
                "WHERE deleted_at IS NULL ORDER BY created_at DESC"
            )
        return [dict(r) for r in await cursor.fetchall()]


async def get_proposal(proposal_id: int, postgres_conn: Any = None) -> dict | None:
    if postgres_conn is not None:
        async with postgres_conn.cursor() as cur:
            await cur.execute(
                f"SELECT {', '.join(_PROPOSAL_COLUMNS)} FROM trade_proposals.proposals "
                "WHERE id = %s AND deleted_at IS NULL",
                (proposal_id,),
            )
            row = await cur.fetchone()
            return dict(zip(_PROPOSAL_COLUMNS, row)) if row else None
    async with aiosqlite.connect(DB_PATH) as db:
        db.row_factory = aiosqlite.Row
        cursor = await db.execute(
            f"SELECT {', '.join(_PROPOSAL_COLUMNS)} FROM trade_proposals WHERE id = ? AND deleted_at IS NULL",
            (proposal_id,),
        )
        row = await cursor.fetchone()
        return dict(row) if row else None


async def resolve_proposal(proposal_id: int, status: str, postgres_conn: Any = None) -> bool:
    """Approve/reject/expire -- only ever fires from a 'pending' row, so an
    already-resolved proposal can't be double-approved by a stale UI state
    or a retried request."""
    if status not in ("approved", "rejected", "expired"):
        raise ValueError(f"resolve_proposal status must be approved/rejected/expired, got {status!r}")
    if postgres_conn is not None:
        async with postgres_conn.cursor() as cur:
            await cur.execute(
                "UPDATE trade_proposals.proposals SET status = %s, resolved_at = (now() AT TIME ZONE 'utc') "
                "WHERE id = %s AND status = 'pending' AND deleted_at IS NULL",
                (status, proposal_id),
            )
            updated = cur.rowcount > 0
        await postgres_conn.commit()
        return updated
    async with aiosqlite.connect(DB_PATH) as db:
        cursor = await db.execute(
            "UPDATE trade_proposals SET status = ?, resolved_at = datetime('now') "
            "WHERE id = ? AND status = 'pending' AND deleted_at IS NULL",
            (status, proposal_id),
        )
        await db.commit()
        return cursor.rowcount > 0


async def mark_command_written(proposal_id: int, postgres_conn: Any = None) -> bool:
    """Flips an 'approved' proposal's command_written_at the instant the Mac
    sync loop writes pcorp_pending_order.json -- the loop's own guard
    against re-writing the command file (and risking a double-execution)
    on its next poll tick before a result has come back yet."""
    if postgres_conn is not None:
        async with postgres_conn.cursor() as cur:
            await cur.execute(
                "UPDATE trade_proposals.proposals SET command_written_at = (now() AT TIME ZONE 'utc') "
                "WHERE id = %s AND status = 'approved' AND command_written_at IS NULL",
                (proposal_id,),
            )
            updated = cur.rowcount > 0
        await postgres_conn.commit()
        return updated
    async with aiosqlite.connect(DB_PATH) as db:
        cursor = await db.execute(
            "UPDATE trade_proposals SET command_written_at = datetime('now') "
            "WHERE id = ? AND status = 'approved' AND command_written_at IS NULL",
            (proposal_id,),
        )
        await db.commit()
        return cursor.rowcount > 0


async def record_execution_result(
    proposal_id: int, success: bool, ticket: str | None, result_summary: str, postgres_conn: Any = None
) -> bool:
    status = "executed" if success else "failed"
    if postgres_conn is not None:
        async with postgres_conn.cursor() as cur:
            await cur.execute(
                "UPDATE trade_proposals.proposals SET status = %s, executed_ticket = %s, executed_result = %s "
                "WHERE id = %s AND status = 'approved'",
                (status, ticket, result_summary, proposal_id),
            )
            updated = cur.rowcount > 0
        await postgres_conn.commit()
        return updated
    async with aiosqlite.connect(DB_PATH) as db:
        cursor = await db.execute(
            "UPDATE trade_proposals SET status = ?, executed_ticket = ?, executed_result = ? "
            "WHERE id = ? AND status = 'approved'",
            (status, ticket, result_summary, proposal_id),
        )
        await db.commit()
        return cursor.rowcount > 0


async def delete_proposal(proposal_id: int, postgres_conn: Any = None) -> bool:
    # Soft delete, same as every other table in this app.
    if postgres_conn is not None:
        async with postgres_conn.cursor() as cur:
            await cur.execute(
                "UPDATE trade_proposals.proposals SET deleted_at = (now() AT TIME ZONE 'utc') "
                "WHERE id = %s AND deleted_at IS NULL",
                (proposal_id,),
            )
            updated = cur.rowcount > 0
        await postgres_conn.commit()
        return updated
    async with aiosqlite.connect(DB_PATH) as db:
        cursor = await db.execute(
            "UPDATE trade_proposals SET deleted_at = datetime('now') WHERE id = ? AND deleted_at IS NULL",
            (proposal_id,),
        )
        await db.commit()
        return cursor.rowcount > 0
