"""
Josh's own logged trade history (2026-09-20, Trade Intelligence pass) --
genuinely separate from trading_division.py's data source: that reads a
sibling repo's read-only research.sqlite (the trading robot's own
backtest/walk-forward/Monte Carlo output), never touched here. This is a
real, writable table Josh populates himself, one trade at a time, backing
Trade Breakdown's pattern-detection.

Own SQLite file (trade_intelligence.db) and own Postgres schema
(trade_intelligence), same "genuinely separate domain" reasoning as
personal.db/alpha_mode.db. Deliberately NOT added to the Stage 3/4
migration tooling (app/migration/manifest.py): that tool's auto-generated
Postgres DDL (replicate.py's _column_def) only carries over column type
and NOT NULL, never a SQLite CHECK constraint -- confirmed directly. Since
setup_tag/timeframe/direction need real, hard-enforced vocabularies (not
just automation_tools.py's soft trigger_tool warning), this table's
Postgres side is created by real inline DDL in init_trade_intelligence_db
instead, with the same CHECK clauses as the SQLite side.

Like every file under backend/data/, this is gitignored -- nothing
written here ever reaches GitHub.
"""

from pathlib import Path
from typing import Any

import aiosqlite

DB_PATH = Path(__file__).parent.parent / "data" / "trade_intelligence.db"

# Fixed vocabularies, not freeform text -- keeps Trade Breakdown's
# pattern-grouping reliable at scale (Josh's own requirement). setup_tag's
# 6 values are Josh's own choice; timeframe's MT5/EA-native list is a
# proposed default (matches the trading robot's own naming), flagged for
# his review since he only confirmed setup_tag directly.
SETUP_TAGS = ("trend_continuation", "reversal", "breakout", "range_bound", "news_event", "other")
TIMEFRAMES = ("M1", "M5", "M15", "M30", "H1", "H4", "D1")

_TRADE_COLUMNS = (
    "id", "symbol", "direction", "entry_price", "exit_price", "entry_timestamp", "exit_timestamp",
    "size", "pnl", "setup_tag", "timeframe", "screenshot_path", "notes", "ai_analysis", "created_at",
)


async def init_trade_intelligence_db(postgres_conn: Any = None) -> None:
    if postgres_conn is not None:
        await _init_postgres(postgres_conn)
        return
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    async with aiosqlite.connect(DB_PATH) as db:
        await db.execute(
            f"""
            CREATE TABLE IF NOT EXISTS trades (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                symbol TEXT NOT NULL,
                direction TEXT NOT NULL CHECK (direction IN ('long', 'short')),
                entry_price REAL NOT NULL,
                exit_price REAL,
                entry_timestamp TEXT NOT NULL,
                exit_timestamp TEXT,
                size REAL NOT NULL,
                pnl REAL,
                setup_tag TEXT NOT NULL CHECK (setup_tag IN {SETUP_TAGS}),
                timeframe TEXT NOT NULL CHECK (timeframe IN {TIMEFRAMES}),
                screenshot_path TEXT,
                notes TEXT,
                ai_analysis TEXT,
                created_at TEXT NOT NULL DEFAULT (datetime('now')),
                deleted_at TEXT
            )
            """
        )
        await db.commit()


async def _init_postgres(conn: Any) -> None:
    async with conn.cursor() as cur:
        await cur.execute("CREATE SCHEMA IF NOT EXISTS trade_intelligence")
        await cur.execute(
            f"""
            CREATE TABLE IF NOT EXISTS trade_intelligence.trades (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                symbol TEXT NOT NULL,
                direction TEXT NOT NULL CHECK (direction IN ('long', 'short')),
                entry_price DOUBLE PRECISION NOT NULL,
                exit_price DOUBLE PRECISION,
                entry_timestamp TEXT NOT NULL,
                exit_timestamp TEXT,
                size DOUBLE PRECISION NOT NULL,
                pnl DOUBLE PRECISION,
                setup_tag TEXT NOT NULL CHECK (setup_tag IN {SETUP_TAGS}),
                timeframe TEXT NOT NULL CHECK (timeframe IN {TIMEFRAMES}),
                screenshot_path TEXT,
                notes TEXT,
                ai_analysis TEXT,
                created_at TEXT NOT NULL,
                deleted_at TEXT
            )
            """
        )
    await conn.commit()


async def add_trade(
    symbol: str,
    direction: str,
    entry_price: float,
    entry_timestamp: str,
    size: float,
    setup_tag: str,
    timeframe: str,
    exit_price: float | None = None,
    exit_timestamp: str | None = None,
    pnl: float | None = None,
    screenshot_path: str | None = None,
    notes: str | None = None,
    ai_analysis: str | None = None,
    postgres_conn: Any = None,
) -> int:
    if postgres_conn is not None:
        return await _add_trade_postgres(
            postgres_conn, symbol, direction, entry_price, entry_timestamp, size, setup_tag, timeframe,
            exit_price, exit_timestamp, pnl, screenshot_path, notes, ai_analysis,
        )
    return await _add_trade_sqlite(
        symbol, direction, entry_price, entry_timestamp, size, setup_tag, timeframe,
        exit_price, exit_timestamp, pnl, screenshot_path, notes, ai_analysis,
    )


async def _add_trade_sqlite(
    symbol, direction, entry_price, entry_timestamp, size, setup_tag, timeframe,
    exit_price, exit_timestamp, pnl, screenshot_path, notes, ai_analysis,
) -> int:
    async with aiosqlite.connect(DB_PATH) as db:
        cursor = await db.execute(
            "INSERT INTO trades "
            "(symbol, direction, entry_price, exit_price, entry_timestamp, exit_timestamp, size, pnl, "
            "setup_tag, timeframe, screenshot_path, notes, ai_analysis) "
            "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
            (
                symbol, direction, entry_price, exit_price, entry_timestamp, exit_timestamp, size, pnl,
                setup_tag, timeframe, screenshot_path, notes, ai_analysis,
            ),
        )
        await db.commit()
        return cursor.lastrowid


async def _add_trade_postgres(
    conn, symbol, direction, entry_price, entry_timestamp, size, setup_tag, timeframe,
    exit_price, exit_timestamp, pnl, screenshot_path, notes, ai_analysis,
) -> int:
    # Real bug found live (2026-09-20): a rejected INSERT (e.g. a bad
    # setup_tag hitting the CHECK constraint) leaves this shared, reused
    # connection in an aborted-transaction state -- every subsequent query
    # on it then fails with "current transaction is aborted" until
    # something rolls it back, taking down every OTHER route sharing this
    # same connection, not just this one. Same class of leak already found
    # and fixed once this session in auth_db.py's verify_device_session.
    # The route layer validates against SETUP_TAGS/TIMEFRAMES/direction
    # before ever calling this, so the CHECK constraint firing here should
    # be unreachable in normal operation -- this is the backstop for that
    # assumption being wrong, not the primary guard.
    try:
        async with conn.cursor() as cur:
            await cur.execute(
                "INSERT INTO trade_intelligence.trades "
                "(symbol, direction, entry_price, exit_price, entry_timestamp, exit_timestamp, size, pnl, "
                "setup_tag, timeframe, screenshot_path, notes, ai_analysis, created_at) "
                "VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, (now() AT TIME ZONE 'utc')) "
                "RETURNING id",
                (
                    symbol, direction, entry_price, exit_price, entry_timestamp, exit_timestamp, size, pnl,
                    setup_tag, timeframe, screenshot_path, notes, ai_analysis,
                ),
            )
            (new_id,) = await cur.fetchone()
        await conn.commit()
        return new_id
    except Exception:
        await conn.rollback()
        raise


async def list_trades(postgres_conn: Any = None) -> list[dict]:
    if postgres_conn is not None:
        async with postgres_conn.cursor() as cur:
            await cur.execute(
                f"SELECT {', '.join(_TRADE_COLUMNS)} FROM trade_intelligence.trades "
                "WHERE deleted_at IS NULL ORDER BY entry_timestamp DESC"
            )
            rows = await cur.fetchall()
            return [dict(zip(_TRADE_COLUMNS, row)) for row in rows]
    async with aiosqlite.connect(DB_PATH) as db:
        db.row_factory = aiosqlite.Row
        cursor = await db.execute(
            f"SELECT {', '.join(_TRADE_COLUMNS)} FROM trades "
            "WHERE deleted_at IS NULL ORDER BY entry_timestamp DESC"
        )
        return [dict(r) for r in await cursor.fetchall()]


async def delete_trade(trade_id: int, postgres_conn: Any = None) -> bool:
    # Soft delete, same as every other table in this app -- nothing is
    # ever hard-deleted.
    if postgres_conn is not None:
        async with postgres_conn.cursor() as cur:
            await cur.execute(
                "UPDATE trade_intelligence.trades SET deleted_at = (now() AT TIME ZONE 'utc') "
                "WHERE id = %s AND deleted_at IS NULL",
                (trade_id,),
            )
            updated = cur.rowcount > 0
        await postgres_conn.commit()
        return updated
    async with aiosqlite.connect(DB_PATH) as db:
        cursor = await db.execute(
            "UPDATE trades SET deleted_at = datetime('now') WHERE id = ? AND deleted_at IS NULL",
            (trade_id,),
        )
        await db.commit()
        return cursor.rowcount > 0


# Session buckets derived from entry_timestamp's UTC hour -- not a stored
# column, Josh's own field list doesn't include one. Proposed boundaries,
# flagged for his review: Asian 00-07, London 08-12, NY 13-20, Other 21-23.
def _session_for_hour(hour: int) -> str:
    if 0 <= hour <= 7:
        return "Asian"
    if 8 <= hour <= 12:
        return "London"
    if 13 <= hour <= 20:
        return "NY"
    return "Other"


def _session_for_row(entry_timestamp: str) -> str:
    # entry_timestamp is always written as ISO 8601 ("YYYY-MM-DDTHH:MM:SS",
    # UTC) by the /trade-intelligence/trades route -- a malformed value
    # here would mean a real bug upstream, not a case to silently paper
    # over, but one bad row still shouldn't take down the whole breakdown.
    try:
        return _session_for_hour(int(entry_timestamp[11:13]))
    except (ValueError, IndexError):
        return "Other"


async def compute_breakdown_stats(postgres_conn: Any = None) -> dict:
    """Deterministic aggregation over already-fetched rows (list_trades) --
    one source of truth in plain Python, not two divergent SQL GROUP BY
    dialects to keep in sync. The Trade Intelligence Agent narrates these
    numbers; it never recomputes or eyeballs the raw trades itself."""
    trades = await list_trades(postgres_conn)
    closed = [t for t in trades if t["pnl"] is not None]

    def _group_stats(rows: list[dict]) -> dict:
        wins = [r for r in rows if r["pnl"] > 0]
        total_pnl = sum(r["pnl"] for r in rows)
        return {
            "count": len(rows),
            "win_rate": len(wins) / len(rows) if rows else 0.0,
            "avg_pnl": total_pnl / len(rows) if rows else 0.0,
            "total_pnl": total_pnl,
        }

    def _grouped_by(key_fn) -> list[dict]:
        groups: dict[str, list[dict]] = {}
        for row in closed:
            groups.setdefault(key_fn(row), []).append(row)
        return [{"group": key, **_group_stats(rows)} for key, rows in sorted(groups.items())]

    return {
        "total_trades": len(trades),
        "closed_trades": len(closed),
        "overall": _group_stats(closed),
        "by_setup_tag": _grouped_by(lambda r: r["setup_tag"]),
        "by_timeframe": _grouped_by(lambda r: r["timeframe"]),
        "by_session": _grouped_by(lambda r: _session_for_row(r["entry_timestamp"])),
    }
